name: pedulilindungi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.3.1
  flutter_svg: ^0.23.0+1
  get: 4.3.8
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: IconsApp
      fonts:
        - asset: assets/fonts/IconsApp.ttf
  assets:
    - assets/icons/
    - assets/models/
    - assets/images/
