/// Flutter icons IconsApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsApp
///      fonts:
///       - asset: fonts/IconsApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsApp {
  IconsApp._();

  static const _kFontFam = 'IconsApp';
  static const String? _kFontPkg = null;

  static const IconData profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_box = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_outline = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live_help = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation_down = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation_left = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation_right = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation_up = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pedulilindungi = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_next = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
